### ISSUE TITLE
Time for release code

### ISSUE THREAD

**Issue by Wh2018** [showlab/mist#1]
Hello, I am very interest in your superior work of Long-form Video Question Answering. When will you release the corresponding code?

**Comment by imtianyufu** [comment]
+1

**Comment by lianglili** [comment]
Hello, I am very interest in your superior work of Long-form Video Question Answering. When will you release the corresponding code?

**Comment by maybelu9** [comment]
Thank you so much for your interest. The code will be released in these one or two months. Thank you for your patience.

**Comment by jfliang3324** [comment]
Hi, I am very interest in your VQA work！ When will you release the corresponding code?

**Comment by maybelu9** [comment]
Thank you for your interest. I'm organizing the code and it will be released in several days.
