### ISSUE TITLE
Code for video division

### ISSUE THREAD

**Issue by Dulpy** [showlab/mist#10]
Could you please show the code for dividing the videos into several segments ? " as "Mist first divides video into several segments" in the  article.

**Comment by maybelu9** [comment]
Thanks for asking. The video segmentation has been implemented in the code. This model uniformly segments the videos. In the feature extraction code, we sampled 32 frames from the video. Then, in the model part, the sampled video frames are resized, completing the segmentation.

**Comment by Dulpy** [comment]
Thanks for your reply, that's helpful
