### ISSUE TITLE
agqa_val_candidates.json is missing

### ISSUE THREAD

**Issue by ontheway-arch** [showlab/mist#2]
FileNotFoundError: [Errno 2] No such file or directory: 'mist_data/data/datasets/agqa/agqa_val_candidates.json'

**Comment by maybelu9** [comment]
I uploaded this file to google drive, kindly download it to your directory. But, it is worth mentioning that this file was actually used during the debugging of the model, and it is not being used in the current version of the model. This is my mistake, and I should comment out the code that loads it.
