### ISSUE TITLE
Could you offer the agqa_test.jsonl?

### ISSUE THREAD

**Issue by LemonQC** [showlab/mist#3]

**Comment by fake-warrior8** [comment]
> _No description provided._

Did you find the agqa_test.jsonl? Where can I download this file?

**Comment by dongfengxijian** [comment]
@LemonQC Did you download  the agqa_test.jsonl and agqa_test_candidates.json files. Can you help me? Thank you a lot!

**Comment by dongfengxijian** [comment]
@fake-warrior8 Did you find the address of the agqa_test.jsonl and agqa_test_candidates.json files?  Where can I download these files?
